// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HipHopPizza.Migrations
{
    [DbContext(typeof(HipHopPizzaDbContext))]
    [Migration("20240416033840_CustomerCreate")]
    partial class CustomerCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hip_hop_pizza.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Calzone",
                            Price = 4
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pizza Margherita",
                            Price = 7
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pizza Burrata and Sausage",
                            Price = 9
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pizza Sausage and Friarielli",
                            Price = 9
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pizza Tuna, Onions and Gorgonzola",
                            Price = 11
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tiramisu",
                            Price = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Crepes with Nutella, Whipped Cream and Strawberries",
                            Price = 6
                        });
                });

            modelBuilder.Entity("hip_hop_pizza.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<int>("CustomerPhone")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text");

                    b.Property<decimal>("Tip")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerEmail = "JdP@hotmail.com",
                            CustomerName = "Order1",
                            CustomerPhone = 1234567,
                            Date = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClosed = true,
                            PaymentType = "Cash",
                            Tip = 5m,
                            Total = 46m,
                            Type = "Pick up",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerEmail = "PizzaPazza@gmail.com",
                            CustomerName = "Order2",
                            CustomerPhone = 2345678,
                            Date = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClosed = false,
                            PaymentType = "Credit Card",
                            Tip = 7m,
                            Total = 52m,
                            Type = "Online",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("hip_hop_pizza.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("hip_hop_pizza.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Uid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pier",
                            Uid = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jean",
                            Uid = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "George",
                            Uid = 3
                        });
                });

            modelBuilder.Entity("hip_hop_pizza.Models.OrderItem", b =>
                {
                    b.HasOne("hip_hop_pizza.Models.Item", "Item")
                        .WithMany("Orders")
                        .HasForeignKey("ItemId");

                    b.HasOne("hip_hop_pizza.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("hip_hop_pizza.Models.Item", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("hip_hop_pizza.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
